language: julia
os:
    - osx
    - linux
julia:
    - 0.4
    - 0.5
    - nightly
notifications:
    email: false

before_install:
  - cd ..
  - git clone https://github.com/wookay/CITestConda.jl.git Conda.jl
  - cd Conda.jl
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew update >/dev/null 2>&1; fi

# Workaround for https://github.com/travis-ci/travis-ci/issues/4942
git:
  depth: 99999
